apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
  namespace: phishing-shield
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      containers:
      - name: image-service
        image: phishing-shield/image-service:2.0.0
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: image-service
  namespace: phishing-shield
spec:
  selector:
    app: image-service
  ports:
  - port: 8000
    targetPort: 8000
